// =============================================================================
// Parsec Apollonian (Coxeter tetrahedral gasket) distance estimator - core
// =============================================================================
//
// Includable chunk (no #version, no main). Concatenated after a #version line
// and before raymarch_main.glsl, like the other DE cores.
//
// The classical 3D Apollonian gasket: four unit spheres at the vertices of a
// regular tetrahedron of edge length 2 (mutually tangent), plus a bounding
// sphere of radius (sqrt(6)+2)/2 by 3D Descartes/Soddy. The limit set of the
// Kleinian group generated by inversions through these five spheres is a
// fractal 2D surface in 3D (Hausdorff dim ~ 2.47).
//
// KEY TRICK: we render the LIMIT SET ITSELF, not the sphere surfaces. The DE
//   DE = de_envelope * exp(-log_scale)
// gives DE ~ de_envelope at the outer shells (scale ~ 1, no inversions yet),
// which lets rays pass straight through them, and DE -> 0 deep in the orbit
// where many inversions have piled up (the limit set). This is what makes the
// result the actual Coxeter gasket and not "spheres with deep stuff hidden
// inside that the ray can't see through". Validated in Python; reference image
// shows the four tetrahedral lobes with recursive triangular sub-gaskets at
// every scale, decreasing toward the centre.
//
// THE MORPH STAR: 'tangency' is a multiplier on the canonical inner-sphere
// centre distance (sqrt(3/2)). At tangency = 1.0 the four spheres are exactly
// mutually tangent and we get the connected Coxeter gasket. tangency < 1
// overlaps them and produces a denser tetrahedral foam; tangency > 1 separates
// them and the limit set fragments into Kleinian fractal dust (Schottky-style).
// One continuous slider, three qualitatively distinct aesthetic regimes -- a
// rare phase-transition slider rather than a smooth deformation.
//
// HALF-CUT: same CSG-intersect-with-half-space idiom as quaternion_julia_core.
// A tilted cut plane exposes a 2D Apollonian gasket cross-section -- itself a
// famous mathematical object -- on the cut face, with the 3D lobes still
// visible behind. Two fractals for the price of one.
//
// PARAMETER REUSE (shared FoldParams buffer, binding 1):
//   iterations    = max inversion-iteration count
//   boxParams     = (tangency, planeOffset, outerRadiusMult, cutEnabled)
//   surfParams    = (planeNormal.xyz, deEnvelope)
//   juliaC        = unused (zero)
//   rot.w         = DE fudge
//   boundSphere   = bounding sphere for the fast skip

layout(std430, binding = 1) readonly buffer FoldParams {
    int   iterations;
    int   mode;             // unused
    int   juliaMode;        // unused
    int   pad0;

    vec4  boxParams;        // (tangency, planeOffset, outerRadiusMult, cutEnabled)
    vec4  surfParams;       // (planeNormal.xyz, deEnvelope)
    vec4  juliaC;           // unused
    vec4  rot;              // (_, _, _, fudge)
    vec4  boundSphere;      // (cx, cy, cz, r)
} fp;

vec4 gTrap;

// Canonical regular-tetrahedron vertices at distance sqrt(3/2) from origin,
// each of edge length 2 from the next -- exactly the configuration for four
// mutually tangent unit spheres. Each row scaled by 'tangency' at use site.
const float SQRT_INV_2 = 0.7071067811865475;       // 1/sqrt(2)
const vec3 INNER_CENTER_0 = vec3( SQRT_INV_2,  SQRT_INV_2,  SQRT_INV_2);
const vec3 INNER_CENTER_1 = vec3( SQRT_INV_2, -SQRT_INV_2, -SQRT_INV_2);
const vec3 INNER_CENTER_2 = vec3(-SQRT_INV_2,  SQRT_INV_2, -SQRT_INV_2);
const vec3 INNER_CENTER_3 = vec3(-SQRT_INV_2, -SQRT_INV_2,  SQRT_INV_2);

// Canonical Soddy bounding curvature gives R = (sqrt(6) + 2)/2.
const float R_INNER          = 1.0;
const float R_OUTER_CANONICAL = 2.2247448713915890;

vec3 innerCenter(int si, float tangency) {
    // GLSL doesn't allow dynamically-indexed const arrays everywhere, so a
    // switch keeps the code portable across drivers.
    if (si == 0) return INNER_CENTER_0 * tangency;
    if (si == 1) return INNER_CENTER_1 * tangency;
    if (si == 2) return INNER_CENTER_2 * tangency;
    return INNER_CENTER_3 * tangency;
}

float estimate(vec3 p) {
    float tangency    = fp.boxParams.x;
    float planeOff    = fp.boxParams.y;
    float outerMult   = fp.boxParams.z;
    bool  cutEnabled  = fp.boxParams.w > 0.5;
    float deEnvelope  = fp.surfParams.w;

    float r2_in  = R_INNER * R_INNER;
    float r_out  = R_OUTER_CANONICAL * outerMult;
    float r2_out = r_out * r_out;

    // Orbit variables.
    vec3  q        = p;
    float logScale = 0.0;
    int   lastSph  = -1;

    // Trap state (mins over the orbit, same packing as the other cores:
    // gTrap = (origin, plane |q.x|, axis |q.xy|, shell)).
    float trapOrigin = 1e20;     // gTrap.x -- min |q| during orbit
    float trapPlaneX = 1e20;     // gTrap.y -- min |q.x| (x=0 plane trap)
    float trapAxisZ  = 1e20;     // gTrap.z -- min length(q.xy) (z-axis trap)
    float trapShell  = 1e20;     // gTrap.w -- min distance to nearest sphere surface

    // Iterate inversions. Each step: if q is inside any inner sphere, invert
    // through it and accumulate log scale; otherwise if q is outside the
    // bounding sphere, invert it back inside. If neither, q has settled in the
    // fundamental ("free") region between the spheres -- stop.
    for (int i = 0; i < fp.iterations; i++) {
        bool inverted = false;

        // Inner spheres. Unrolled-via-loop with early break on the first hit.
        for (int si = 0; si < 4; si++) {
            vec3 c = innerCenter(si, tangency);
            vec3 d = q - c;
            float d2 = dot(d, d);
            if (d2 < r2_in) {
                float k = r2_in / max(d2, 1e-30);
                q       = c + d * k;
                logScale += log(k);
                lastSph = si;
                inverted = true;
                break;
            }
        }

        // Bounding sphere (centred at origin) -- only if no inner inversion fired.
        if (!inverted) {
            float d2o = dot(q, q);
            if (d2o > r2_out) {
                float k = r2_out / max(d2o, 1e-30);
                q       = q * k;
                logScale += log(k);
                lastSph = 4;
                inverted = true;
            }
        }

        if (!inverted) break;   // escaped to free region

        // Update orbit traps from the post-inversion position.
        float qlen = length(q);
        trapOrigin = min(trapOrigin, qlen);
        trapPlaneX = min(trapPlaneX, abs(q.x));
        trapAxisZ  = min(trapAxisZ,  length(q.xy));
        // Shell trap: distance to nearest sphere surface (any of the 5).
        float shell = abs(qlen - r_out);
        shell = min(shell, abs(length(q - innerCenter(0, tangency)) - R_INNER));
        shell = min(shell, abs(length(q - innerCenter(1, tangency)) - R_INNER));
        shell = min(shell, abs(length(q - innerCenter(2, tangency)) - R_INNER));
        shell = min(shell, abs(length(q - innerCenter(3, tangency)) - R_INNER));
        trapShell = min(trapShell, shell);
    }

    // DE: outer shells (logScale ~ 0) -> DE ~ deEnvelope, ray passes through;
    // limit set (logScale -> +inf) -> DE -> 0, ray hits.
    float de = deEnvelope * exp(-logScale);

    // Pack traps. Categorical last-sphere mixed in lightly via the plane trap
    // so the four lobes get distinguishable hue bands without breaking the
    // smooth palette gradient.
    gTrap = vec4(trapOrigin, trapPlaneX + 0.15 * float(lastSph), trapAxisZ, trapShell);

    // Half-cut: CSG intersection with a half-space (max of signed distances).
    // Guard: normalize(0) is NaN and max(de, NaN) poisons the march, so an
    // unset plane normal means "no cut" rather than garbage pixels.
    if (cutEnabled && dot(fp.surfParams.xyz, fp.surfParams.xyz) > 1e-12) {
        vec3 n = normalize(fp.surfParams.xyz);
        float plane = dot(p, n) - planeOff;
        de = max(de, plane);
    }

    return de;
}

vec4 attractorBoundingSphere() {
    return fp.boundSphere;
}

float deFudge() {
    return fp.rot.w;
}
